version: "3.9"

services:
  app:
    build: .
    container_name: yoga_app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///./data/database.sqlite3
      - NOTIFIER_LOGIN=${NOTIFIER_LOGIN}
      - NOTIFIER_PASSWORD=${NOTIFIER_PASSWORD}
      - AUTH_SECRET=${AUTH_SECRET}
      - CONFIG=${CONFIG}
    volumes:
      - sqlite_data:/app/data

    restart: on-failure

volumes:
  sqlite_data:
